import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Agentic AI Systems Research Project
  agenticAISidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction to Agentic AI Systems',
    },
    {
      type: 'category',
      label: 'Chapter 1: Setup',
      items: [
        {
          type: 'doc',
          id: 'chapter-1/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-1/setup',
          label: 'Environment Setup'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 2: Constitution',
      items: [
        {
          type: 'doc',
          id: 'chapter-2/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-2/constitution',
          label: 'Constitution Framework'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 3: Specification',
      items: [
        {
          type: 'doc',
          id: 'chapter-3/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-3/specification',
          label: 'Specification Process'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 4: Planning',
      items: [
        {
          type: 'doc',
          id: 'chapter-4/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-4/planning',
          label: 'Planning Methodologies'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 5: Implementation',
      items: [
        {
          type: 'doc',
          id: 'chapter-5/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-5/implementation',
          label: 'Implementation Patterns'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 6: Advanced Agentic Patterns',
      items: [
        {
          type: 'doc',
          id: 'chapter-6/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-6/advanced-patterns',
          label: 'Advanced Techniques'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 7: Evaluation',
      items: [
        {
          type: 'doc',
          id: 'chapter-7/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-7/evaluation',
          label: 'Evaluation Methods'
        }
      ],
      collapsed: false
    },
    {
      type: 'category',
      label: 'Chapter 8: Future Work',
      items: [
        {
          type: 'doc',
          id: 'chapter-8/index',
          label: 'Overview'
        },
        {
          type: 'doc',
          id: 'chapter-8/future-work',
          label: 'Future Directions'
        }
      ],
      collapsed: false
    }
  ],
};

export default sidebars;
